#define LGP_RUS
//#define LGP_ENG

#define LGP_MAIN_ELF_NAME        "cMPaB v0.5f (C)Vedan,(i)Tolsi"

#ifdef  LGP_RUS
#define LGP_CONFIG_CLOSE_CMPAB   "Закрыть cMPab"
#define LGP_CONFIG_SETTINGS      "Настройки"
#define LGP_CONFIG_MB_CSM        "CSM МедиаБазы"
#define LGP_CONFIG_KILL_BASE     "Закрыть МедиаБазу"
#define LGP_CONFIG_TAKTS         "Такты"
#define LGP_CONFIG_HELLO_MSG     "Приветствие"
#define LGP_CONFIG_RECO_MSG      "Сообщение реконфигурации"
#define LGP_CONFIG_TIME_SET      "Время"
#define LGP_CONFIG_TIME_HOUR     "Часы"
#define LGP_CONFIG_TIME_MINUTES  "Минуты"
#define LGP_CONFIG_ENABLE        "Включить"
#define LGP_CONFIG_PERCENTS      "Проценты"
#define LGP_CONFIG_SHUTDOWN      "Выключить"
#define LGP_CONFIG_REBOOT        "Перезагрузка"
#define LGP_CONFIG_LOCK          "Блокировать"
#define LGP_CONFIG_CURTAIL       "Свернуть всё"
#define LGP_CONFIG_BY_MSG        "Прощание"
#define LGP_CONFIG_BY_MSG_TEXT   "Текст"
#define LGP_CONFIG_BY_TEXT       "Доброй ночи!"
#define LGP_CONFIG_ACTIONS       "Действия"
#define LGP_CONFIG_ACT_MP        "МедиаПлеер"
#define LGP_CONFIG_ACT_PHONE     "Телефон"
#define LGP_CONFIG_PLAYER_KILL   "Вырубить"
#define LGP_CONFIG_PLAYER_STOP   "Остановить"
#define LGP_CONFIG_PLAYER_PAUSE  "Пауза"
#define LGP_CONFIG_NONE          "Ничего"
#define LGP_MAIN_INST_MSG        "cMPaB\n(c)Vedan\n(i)Tolsi\nустановлен!"
#define LGP_MAIN_UPDT_MSG        "cMPaB:\nКонфиг\nизменён."
#endif 

#ifdef  LGP_ENG
#define LGP_CONFIG_CLOSE_CMPAB   "Kill cMPab"
#define LGP_CONFIG_SETTINGS      "MainSettings"
#define LGP_CONFIG_MB_CSM        "CSM MediaBase"
#define LGP_CONFIG_KILL_BASE     "Kill MediaBase"
#define LGP_CONFIG_TAKTS         "Takts"
#define LGP_CONFIG_HELLO_MSG     "Hello Msg"
#define LGP_CONFIG_RECO_MSG      "Reconfigure Msg"
#define LGP_CONFIG_TIME_SET      "Time"
#define LGP_CONFIG_TIME_HOUR     "Hour"
#define LGP_CONFIG_TIME_MINUTES  "Minutes"
#define LGP_CONFIG_ENABLE        "Enable"
#define LGP_CONFIG_PERCENTS      "Percents"
#define LGP_CONFIG_SHUTDOWN      "ShutDown"
#define LGP_CONFIG_REBOOT        "ReBoot"
#define LGP_CONFIG_LOCK          "Lock"
#define LGP_CONFIG_CURTAIL       "Curtail all"
#define LGP_CONFIG_BY_MSG        "By Msg"
#define LGP_CONFIG_BY_MSG_TEXT   "Text"
#define LGP_CONFIG_BY_TEXT       "GOOD NIGHT!"
#define LGP_CONFIG_ACTIONS       "Actions"
#define LGP_CONFIG_ACT_MP        "MediaPlayer"
#define LGP_CONFIG_ACT_PHONE     "Phone"
#define LGP_CONFIG_PLAYER_KILL   "Kill"
#define LGP_CONFIG_PLAYER_STOP   "Stop"
#define LGP_CONFIG_PLAYER_PAUSE  "Pause"
#define LGP_CONFIG_NONE          "None"
#define LGP_MAIN_INST_MSG        "cMPaB\n(c)Vedan\n(i)Tolsi\ninstall!"
#define LGP_MAIN_UPDT_MSG        "cMPaB:\nConfig\nupdated!"
#endif
