
#define ELFNAME		"MyMenu2_Editor"
#define COPYRIGHT	"MyMenu2_Editor\n(c)BingK(binghelingxi)"
#define LGP_SELECT	"Select"
#define LGP_BACK	"Back"
#define LGP_OPTIONS	"Option"
#define LGP_EDIT	"Edit"
#define LGP_ADD		"Add"
#define LGP_INSERT	"Insert"
#define LGP_DELETE	"Delete"
#define LGP_MENU	"Menu"
#define LGP_EXIT	"Exit"
#define LGP_FUNC	"Func:"
#define LGP_NAME	"Name:"
#define LGP_UP		"Up"
#define LGP_DOWN	"Down"
#define ERR_STR		"ERR!"
#define _percent_t		"%t"
#define LGP_SLECET_FOLDER	"Select folder"
#define LGP_SLECET_FILE	 	"Select file"
