#define LG_MENU_ITENS "Menu Settings"
  #define LG_POS_SAVE "Save pos after exit?"
  #define LG_OTSTUP1 "Move on verticle"
  #define LG_ITEM_NAME "Name of item"
  #define LG_CADRI "Number of animation frames"
  #define LG_ITEM_PASS "Password paragraph?"
  #define LG_CLOSE_MENU "Close menu at open paragraph?"
  #define LG_TYPE "Action"
    #define LG_ITEM1 "\"Contacts\""
    #define LG_ITEM2 "\"Call records\""
    #define LG_ITEM3 "\"Internet""
    #define LG_ITEM4 "\"Camera\""
    #define LG_ITEM5 "\"Messages\""
    #define LG_ITEM6 "\"Organiser\""
    #define LG_ITEM7 "\"Games\""
    #define LG_ITEM8 "\"Media player\""
    #define LG_ITEM9 "\"Alarm clock""
    #define LG_ITEM10 "\"Extras\""
    #define LG_ITEM11 "\"My stuff""
    #define LG_ITEM12 "\"Setup""

#define LG_ICON "Setting items"
#define LG_PODNYAT  "Raise up to"
#define LG_OTSTUP_X "Inc. distance from X to"
#define LG_OTSTUP_Y "Inc. distance from Y to"

#define LG_ANI_ITEM "Preset Animation"
  #define LG_ON_ANI "on animation"
  #define LG_ANI_INVERT "Invert animation?"
  #define LG_SPEED_ANI "Animation speed"
  #define LG_SEL_KADR "Frame allocation"
  #define LG_ANI "Discard the frame when navigating?"

//Пароль на пунт?меню
#define LG_PASS_OF_MENU "Password on the menu"
  #define LG_PASS "Password"
  #define LG_PASS_IN_START "Password when open menu?"
  #define LG_AVTO_PROV "Autologin with the correct password?"
  #define LG_W_P_WINDOW "Text"

//Настройа окна "Ввод паро?"
  #define LG_PASS_OPT "Setting\"Enter password\""
    #define LG_ENTER_COLOR "Color label"

    #define LG_VIEW_COLOR "Color \"***\""
    #define LG_WIN_POS "Window position"
    #define LG_HE_POS "Location"
    #define LG_HE_COLOR "Font Color"
